# Generated by Django 4.1.6 on 2023-02-17 03:31

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_cover',
            field=models.ImageField(blank=True, default='default-image.jpg', null=True, upload_to=''),
        ),
    ]
